tasks:
  - command: pip3 install -U platformio && platformio run -e tasmota

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - Atishay-Jain.All-Autocomplete
    - shardulm94.trailing-spaces
