name: Berry solidify

on:
  workflow_dispatch:      # Manually start a workflow
  push:
    branches: gh_solidify


jobs:
  be_solidify:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Make Berry and Tasmota Berry code
        run: |
          cd lib/libesp32/berry
          make
          cd ../berry_tasmota
          ../berry/berry -s -g solidify_all.be
          cd lib/libesp32/berry_matter
          ../berry/berry -s -g solidify_all.be
