name: Berry solidify

on:
  workflow_dispatch:      # Manually start a workflow
  push:
    branches: gh_solidify


jobs:

  be_solidify:
    name: Generate solidified Berry code
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Make Berry and Tasmota Berry code
        run: |
          cd lib/libesp32/berry
          make
          cd ../berry_tasmota
          ../berry/berry -s -g solidify_all.be
          cd lib/libesp32/berry_matter
          ../berry/berry -s -g solidify_all.be
      - name: Upload Berry Matter solidified code
      - uses: actions/upload-artifact@v3
        with:
          name: berry_matter
          path: ./lib/libesp32/berry_matter/src/solidify
      - name: Upload Berry Tasmota solidified code
      - uses: actions/upload-artifact@v3
        with:
          name: berry_tasmota
          path: ./lib/libesp32/berry_tasmota/src/solidify

  push_solidified:
    needs: be_solidify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Remove old solidified code
        run: |
          rm ./lib/libesp32/berry_tasmota/src/solidify/*
          rm ./lib/libesp32/berry_tasmota/src/solidify/*
      - name: Download solidified Matter Berry code
        uses: actions/download-artifact@v3
        with:
          name: berry_matter
          path: ./lib/libesp32/berry_matter/src/solidify
      - name: Download solidified Tasmota Berry code
        uses: actions/download-artifact@v3
        with:
          name: berry_tasmota
          path: ./lib/libesp32/berry_tasmota/src/solidify
      - name: Move new solidified code back in folder
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Solidified Code updated
